import React from 'react'

export default function B6() {
  return (
    <div>
      <h1>bài 6</h1>
      <div className='w-[500px] h-[200px] overflow-y-scoll text-clip overflow-hidden'>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corrupti, deserunt! Sed, quidem possimus molestias explicabo dolore facere nobis eaque quos excepturi laudantium animi, optio mollitia architecto, tenetur pariatur deserunt iusto!
      Reprehenderit rerum nostrum voluptatibus corporis excepturi itaque quibusdam libero perspiciatis tempore maxime, magnam repellendus quis, odit aliquid qui. Tenetur praesentium quisquam dolor error mollitia expedita saepe ipsa fugit a eius.
      Totam rem asperiores quaerat iure, quasi ea sapiente alias optio quo eveniet natus porro dolor molestias eum assumenda quas distinctio ratione. Quaerat laboriosam corrupti est ratione voluptatum suscipit expedita veniam.
      Pariatur, tenetur temporibus. Quod, magni. Dolorum labore ipsam molestiae nam expedita eius sed necessitatibus dolore delectus recusandae quos officiis harum totam asperiores, ratione minus! Libero velit veritatis ipsa repellat modi.
      Ratione distinctio, deserunt ipsum numquam cum laudantium quos minus non corrupti nihil quae vitae odit, provident architecto ex temporibus optio dolore a? Provident, aliquid fugiat. Quasi quam sunt nihil optio!
      Maiores, quo voluptatum cumque illum qui cum nesciunt! Minus natus tempora repellat exercitationem! Explicabo eligendi est laboriosam quae quos dicta eaque maiores pariatur nobis sed cupiditate quam doloremque, unde maxime!
      Praesentium architecto facilis tempore accusantium tenetur cum omnis alias corporis distinctio, earum, officiis sit iusto aspernatur illo tempora. Iusto consectetur assumenda doloribus! Autem eos nobis ipsum, excepturi beatae quo quae.
      Hic ea optio earum molestias explicabo est eaque minima ut dolore assumenda voluptatibus rem repudiandae quam, praesentium quas laboriosam odio commodi iure quos nostrum. Dolorem hic ex consectetur libero velit?
      Illo expedita distinctio odit repellat in aliquid quia animi placeat ad dolor harum facilis, maxime fuga iure, rerum possimus ullam voluptate neque enim sapiente natus est? Sunt aperiam at culpa.
      Cum porro mollitia accusamus recusandae laboriosam dolor blanditiis autem, exercitationem libero quibusdam, dolores a ut inventore dignissimos repudiandae ullam? Incidunt ducimus, ipsa at hic debitis illum maiores voluptas qui fugit.
      Explicabo eaque officia consequuntur magnam consectetur consequatur tempore soluta sed debitis ad, libero quis rerum tenetur eius maiores voluptas vel nisi mollitia! Nulla incidunt doloribus quia amet, dicta sequi quam?
      Sit, aperiam ullam nesciunt repudiandae quis autem consequatur eum qui eaque ipsa odit officiis error voluptatibus mollitia, exercitationem adipisci harum aspernatur alias consectetur. Consequuntur voluptatum delectus animi asperiores consequatur. Eos.
      Veniam ducimus sit sunt ut voluptatem alias ea. Praesentium soluta explicabo nemo odit sunt, consequuntur quisquam deleniti saepe cum temporibus at quia rem maiores distinctio iusto provident. Totam, voluptatem. Laborum.
      Quis sequi nulla, vero saepe rerum asperiores tempore necessitatibus nostrum itaque! Praesentium, temporibus commodi ducimus eius, reiciendis deserunt magnam sunt corrupti dicta incidunt hic ipsam nemo? Amet quidem odit obcaecati!
      Facilis iusto non, est omnis vel ea voluptatem officia pariatur maxime dolores excepturi culpa ex dolore sapiente rem debitis distinctio enim architecto asperiores velit in dignissimos! Eos, sequi voluptatum. Nesciunt!
      Mollitia odit ratione, molestias, enim commodi nostrum possimus alias praesentium, facilis non ea assumenda. Non dolores praesentium ipsum? Molestias itaque nemo accusamus dolorum praesentium fugiat incidunt totam ipsam consequuntur laudantium?
      Totam velit harum facere voluptates placeat ratione nulla eos nam, et eum accusamus laborum nihil tempora nostrum a ex repellat soluta voluptatem eaque cum inventore vel dolore commodi vitae. Voluptatum.
      Cumque consectetur facilis expedita a quos dolorem repellendus, minus, suscipit vitae corrupti voluptate dolor incidunt pariatur rem reiciendis perspiciatis aperiam? Veritatis labore facere, distinctio excepturi error ipsa deserunt magni facilis.
      Minima dolore eaque consectetur quis tempore incidunt sunt rerum, et, repellat dignissimos corrupti illo optio ut impedit fugit nobis adipisci iste voluptate asperiores libero obcaecati reiciendis dolorem delectus. Odit, unde.
      Necessitatibus commodi maiores beatae quaerat, ut porro ab quod, sint, modi assumenda magni delectus natus repellendus numquam! Vitae temporibus sit totam distinctio, doloribus dolorem et ipsa dignissimos! Unde, beatae autem.
      Exercitationem omnis, eius nulla unde esse similique ipsa in nobis voluptatum expedita distinctio minus consequuntur iusto magnam sunt, accusantium officiis repellendus alias impedit accusamus. Sunt quae laudantium veniam molestiae quo.
      Consectetur voluptas et accusamus aperiam, nisi error ex molestiae quae recusandae ipsum corrupti placeat perspiciatis sint temporibus dolores velit veritatis dignissimos animi tempore quas beatae alias eum blanditiis! Sapiente, veniam?
      Aspernatur corporis quisquam libero rerum dolor, minima reprehenderit delectus, tempore accusantium dolores voluptatibus recusandae nam voluptate iste, nulla blanditiis similique animi et sequi officia eos temporibus vitae? Assumenda, inventore suscipit.
      Reiciendis tempore error sint porro velit architecto blanditiis qui iure mollitia, dignissimos est assumenda quaerat impedit rem incidunt recusandae repellendus exercitationem, rerum consequatur sed, consequuntur nisi. Cumque aperiam accusantium officiis.
      Distinctio cumque quia incidunt harum nisi porro omnis cum consequatur officia. Velit, maiores repellat, fuga vel modi praesentium eligendi aliquam unde blanditiis suscipit vero veniam, inventore quas ab excepturi sunt.
      Iste debitis dignissimos in recusandae, at natus sunt inventore quos aperiam culpa aspernatur rerum? Voluptatibus temporibus dolorem numquam, incidunt et amet earum! Delectus id voluptates, praesentium error labore ea rerum.
      Possimus alias perspiciatis architecto deserunt culpa optio? Reiciendis ex alias nihil quos, voluptas similique aperiam saepe perferendis porro facere a beatae unde neque dicta eum soluta dolorum accusamus deserunt reprehenderit!
      Fuga quod, optio maxime labore, pariatur nulla explicabo perferendis quae, quisquam repellendus eaque iste ullam iure corrupti atque! Doloremque tempora debitis illum possimus et alias adipisci quisquam sapiente hic facere?
      Quae expedita ullam reprehenderit iure mollitia, explicabo accusantium nobis fuga dolorem assumenda harum minus doloribus dolor pariatur nisi reiciendis cumque molestiae. Optio saepe maiores nesciunt ipsam sint. Voluptatum, cum. A?
      Harum illo excepturi, nobis sed quae dignissimos eveniet, nihil fugit similique sint voluptates iure magnam rerum aperiam sequi? Eveniet, deleniti nisi pariatur facere magnam mollitia ipsum sunt in nostrum ducimus.
      Blanditiis optio ipsa repudiandae expedita voluptate, tempore eum dolor? Quisquam dicta ducimus et, voluptas ipsam animi autem, cumque eius illo iusto vel, incidunt voluptatibus! Dolores adipisci ducimus harum corrupti blanditiis.
      Maiores reiciendis iusto illo inventore unde ex quibusdam suscipit modi ullam ad qui aut dicta itaque, provident culpa nostrum praesentium nam exercitationem reprehenderit voluptatibus quae adipisci possimus consequatur. Itaque, assumenda.
      Delectus alias, minus dolores excepturi provident ab magni nihil atque culpa sunt explicabo ipsam, officia incidunt quibusdam dignissimos impedit illum quas voluptatum fugiat. Sint mollitia nobis architecto unde dolorum rerum!
      Ratione officiis mollitia laborum unde, reiciendis vel et nesciunt expedita beatae cupiditate quaerat magnam autem natus ut minima maiores repellat! Sint minus praesentium assumenda ad tenetur. Omnis tempore aspernatur illo.
      Dolorem nostrum sit perspiciatis! Id fugiat voluptatum quasi explicabo facilis labore quidem magni harum illo minus in deserunt, inventore, recusandae delectus dicta deleniti reprehenderit repellat iure earum laudantium autem doloremque.
      Neque culpa dolores dolorum! Quas possimus voluptate aperiam dolorem explicabo minima accusantium repellendus. Consequatur, consectetur consequuntur. Fugit dolor nihil, eaque aspernatur quam maiores obcaecati tenetur consequatur eligendi quas blanditiis minus!
      Neque exercitationem sapiente totam qui, facilis veniam, dolorem nihil amet natus harum accusantium reprehenderit mollitia. Accusamus et vero laboriosam voluptatem quibusdam molestias! Consectetur expedita ratione officiis, vel temporibus et mollitia!
      Mollitia, itaque obcaecati repellat nostrum, velit hic distinctio sapiente autem nesciunt corporis dicta cupiditate, nemo quibusdam magni odit quod illum ullam eaque dolorum labore quasi. Inventore laboriosam dignissimos nisi eaque?
      Nemo, a! Minus aliquam ullam qui iusto mollitia hic veniam, quibusdam assumenda. Dignissimos nulla exercitationem ut repudiandae necessitatibus hic voluptatibus reprehenderit, pariatur quod nam, aut esse architecto ipsum, laudantium minus.
      Eius perspiciatis odio possimus tenetur dolor cupiditate. Modi aperiam perferendis mollitia natus, nisi deserunt porro laborum? Quos vel ex excepturi iure totam. Architecto, saepe ab nobis sunt culpa impedit quas.
      Eaque porro aspernatur magnam asperiores perspiciatis beatae praesentium maiores natus dignissimos dolores ut velit modi, laboriosam fugiat libero tenetur. Illo, neque voluptatem animi corporis doloribus quas porro vel perspiciatis facilis!
      Assumenda sint id ea cum repudiandae? Quae corrupti illum consequatur officiis? Minima esse maiores reprehenderit corporis cupiditate deleniti, beatae optio inventore voluptatibus non, aperiam illum doloribus porro sequi, consequuntur quia.
      Laboriosam, magnam quisquam cupiditate veritatis error libero natus quis necessitatibus possimus officia magni pariatur quidem esse, voluptas, dolores sint. Expedita corporis sunt perspiciatis consequatur totam consectetur, quidem laudantium suscipit hic.
      Voluptatem non, nihil voluptates officiis, libero impedit facere repellendus autem suscipit illo atque doloribus quasi, reprehenderit neque. Natus harum iure earum illum odit necessitatibus hic, nemo nobis, consequatur tenetur sunt?
      Quae adipisci eos rem deserunt voluptatem aut vero hic veritatis voluptatum nesciunt neque iste ut culpa et, corrupti expedita ad? Placeat consequatur dolorum velit sint eos repudiandae aspernatur, quidem perspiciatis?
      Excepturi delectus maxime hic dolorem autem eum sit! Aspernatur nemo eaque assumenda quibusdam, nam molestias ad laboriosam hic nostrum temporibus? Sint eius necessitatibus vel quod, obcaecati ad sequi dolores officiis.
      Quaerat cupiditate cum autem. Illo nesciunt laudantium nobis? Quasi harum consequatur itaque illum explicabo asperiores corporis mollitia, nisi temporibus rerum tempora omnis veritatis suscipit et perspiciatis, magnam quod ea magni.
      Eaque laborum, harum vero debitis error quod cum praesentium, provident deserunt obcaecati labore rem dolores magnam neque. Aperiam libero omnis eum, iure amet cum! Officia enim saepe ullam numquam aspernatur!
      Ut labore cumque vel ullam aspernatur, officiis corporis nesciunt magni dignissimos. Ratione maxime aliquid quam delectus excepturi ea magnam voluptates. Quibusdam aliquid reprehenderit dolor aut facere quos neque ratione libero.
      Excepturi laborum voluptatibus deserunt dolor quisquam nam, voluptatem accusantium, voluptates libero dicta eligendi dolores a cumque, cupiditate quaerat repellat reprehenderit exercitationem sint. Nihil error fugiat exercitationem voluptates nulla ducimus at?</div>
    </div>
  )
}
